language: python
python:
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y gnat
  - sudo apt-get install -y fpc
  - sudo apt-get install -y ash
  - sudo apt-get install -y csh
  - sudo apt-get install -y ksh
  - sudo apt-get install -y racket
  - sudo apt-get install -y scala
  - sudo apt-get install graphviz
# sudo apt-get install julia

script: python3 -m unittest letscode.py
