language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq

install:
  - pip install pep8
  - pip install --upgrade pyflakes
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y gnat
  - sudo apt-get install -y fpc
  - sudo apt-get install -y ash
  - sudo apt-get install -y csh
  - sudo apt-get install -y ksh
  - sudo apt-get install -y yash
  - sudo apt-get install -y racket
  - sudo apt-get install -y scala
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y swi-prolog
  - sudo apt-get install -y valac
  - sudo apt-get install -y tcsh
  - sudo apt-get install -y zsh
  - sudo apt-get install -y coq
  - sudo apt-get install -y r-base
  - sudo apt-get install -y scilab
  - sudo apt-get install -y octave
  - sudo apt-get install -y clisp
  - sudo apt-get install -y gforth
  - sudo apt-get install -y open-cobol
  - sudo apt-get install -y ghc
  - sudo apt-get install -y gdc
  - sudo apt-get install -y gnu-smalltalk
  - sudo apt-get install -y groovy
  - sudo apt-get install -y pike7.8
  - sudo apt-get install -y fish
  - sudo apt-get install -y verilog
  - sudo apt-get install -y slsh
  - sudo apt-get install -y icont
# sudo apt-get install -y mozart
# sudo apt-get install -y gccgo -> not enough to make golang compile properly
# sudo apt-get install -y mit-scheme -> "E: Sub-process /usr/bin/dpkg returned an error code (1)" to be investigated
# sudo apt-get install -y rustc
# sudo apt-get install -y julia
# sudo apt-get install -y php
# sudo apt-get install -y lua

before_script:
 - pyflakes .
 - pep8 *.py --ignore=E501,E713
  # to have the list anyway
 - pep8 *.py --select=E501,E713 || true

script:
 - python3 -m unittest discover --pattern=*.py
